version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server_2022
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd123"   # must meet complexity rules
      MSSQL_PID: "Developer"                        # e.g. Developer, Express, etc.
      # You can optionally add more environment variables if you like:
      # MSSQL_COLLATION: "SQL_Latin1_General_CP1_CS_AS"
      MSSQL_TCP_PORT: "1433"
      # MSSQL_MEMORY_LIMIT_MB: "2048"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd123 -Q \"SELECT 1\" || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always

volumes:
  mssql_data:

